name: Firebase Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Firebase
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Step 3: Install Firebase CLI
      - name: Install Firebase CLI
        run: |
          npm install -g firebase-tools

      # Step 4: Authenticate with Firebase
      - name: Firebase Authentication
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: firebase projects:list

      # Step 5: Deploy to Firebase
      - name: Deploy to Firebase
        run: firebase deploy
